#Containers' name can't contain _ (underscore) because scrapy is not able to handle it.

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - "ES_JAVA_OPTS=-Xmx4g -Xms4g"
      #  - ELASTIC_PASSWORD=reZeP6crgHBGVsKeAFyWnduTzcwyB4qR
      #  - xpack.monitoring.collection.enabled=true
      #  - xpack.monitoring.exporters.remote.type=http
      #  - xpack.monitoring.exporters.remote.host=monitor
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      #  - xpack.license.self_generated.type=basic
      #  - xpack.security.enabled=true
      #  - xpack.security.http.ssl.enabled=true
      #  - xpack.security.http.ssl.key=$ELK_CERTS_DIR/elasticsearch1/elasticsearch1.key
      #  - xpack.security.http.ssl.certificate_authorities=$ELK_CERTS_DIR/ca/ca.crt
      #  - xpack.security.http.ssl.certificate=$ELK_CERTS_DIR/elasticsearch1/elasticsearch1.crt
      #  - xpack.security.transport.ssl.enabled=true
      #  - xpack.security.transport.ssl.verification_mode=certificate
      #  - xpack.security.transport.ssl.certificate_authorities=$ELK_CERTS_DIR/ca/ca.crt
      #  - xpack.security.transport.ssl.certificate=$ELK_CERTS_DIR/elasticsearch1/elasticsearch1.crt
      #  - xpack.security.transport.ssl.key=$ELK_CERTS_DIR/elasticsearch1/elasticsearch1.key
      - indices.query.bool.max_clause_count=10240
    #    ulimits:
    #      memlock:
    #        soft: -1
    #        hard: -1
    volumes:
      - .data/elasticsearch1:/var/lib/elasticsearch/data
      - ./elk-certs:$ELK_CERTS_DIR
    ports:
      - "0.0.0.0:9200:9200"
    container_name: "darkweb-search-engine-elasticsearch1"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch2
      - "ES_JAVA_OPTS=-Xmx4g -Xms4g"
      #  - ELASTIC_PASSWORD=reZeP6crgHBGVsKeAFyWnduTzcwyB4qR
      #  - xpack.monitoring.collection.enabled=true
      #  - xpack.monitoring.exporters.remote.type=http
      #  - xpack.monitoring.exporters.remote.host=monitor
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      #  - xpack.license.self_generated.type=basic
      #  - xpack.security.enabled=true
      #  - xpack.security.http.ssl.enabled=true
      #  - xpack.security.http.ssl.key=$ELK_CERTS_DIR/elasticsearch2/elasticsearch2.key
      #  - xpack.security.http.ssl.certificate_authorities=$ELK_CERTS_DIR/ca/ca.crt
      #  - xpack.security.http.ssl.certificate=$ELK_CERTS_DIR/elasticsearch2/elasticsearch2.crt
      #  - xpack.security.transport.ssl.enabled=true
      #  - xpack.security.transport.ssl.verification_mode=certificate
      #  - xpack.security.transport.ssl.certificate_authorities=$ELK_CERTS_DIR/ca/ca.crt
      #  - xpack.security.transport.ssl.certificate=$ELK_CERTS_DIR/elasticsearch2/elasticsearch2.crt
      #  - xpack.security.transport.ssl.key=$ELK_CERTS_DIR/elasticsearch2/elasticsearch2.key
      - indices.query.bool.max_clause_count=10240
    #    ulimits:
    #      memlock:
    #        soft: -1
    #        hard: -1
    volumes:
      - .data/elasticsearch2:/var/lib/elasticsearch/data
      - ./elk-certs:$ELK_CERTS_DIR
    # ports:
    #   - "127.0.0.1:9201:9200"
    container_name: "darkweb-search-engine-elasticsearch2"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch1:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
      - NODE_OPTIONS="--max-old-space-size=8192"
      #  - xpack.monitoring.ui.container.elasticsearch.enabled=true
      #  - xpack.security.transport.ssl.verification_mode=certificate
      - elasticsearch.requestTimeout=300000
      - elasticsearch.startupTimeout=500000
    #  - ELASTICSEARCH_USERNAME=
    #  - ELASTICSEARCH_PASSWORD=
    #  - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$ELK_CERTS_DIR/ca/ca.crt
    #  - SERVER_SSL_ENABLED=true
    #  - SERVER_SSL_KEY=$ELK_CERTS_DIR/kibana/kibana.key
    #  - SERVER_SSL_CERTIFICATE=$ELK_CERTS_DIR/kibana/kibana.crt
    volumes:
      - ./elk-certs:$ELK_CERTS_DIR
    ports:
      - "0.0.0.0:5601:5601"
    restart: always
    container_name: "darkweb-search-engine-kibana"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"

  web-general:
    build: ./web-general
    restart: always
    ports:
      - "0.0.0.0:7000:5000"
    volumes:
      - ./etc:/opt/torscraper/etc:ro
      - ./scripts:/opt/torscraper/scripts:ro
      - ./lib:/opt/torscraper/lib:ro
      - ./web-general:/opt/torscraper/web
    depends_on:
      - db
      - elasticsearch1
      - elasticsearch2
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=toruser
      - MYSQL_PASSWORD=torpass
      - MYSQL_DATABASE=tor
      - DATABASE_POOL_SIZE=20
      - DATABASE_POOL_RECYCLE=3600
      - DATABASE_MAX_OVERFLOW=30
    container_name: "darkweb-search-engine-web-general"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"

  db:
    build: db
    ports:
      - "0.0.0.0:3307:3306"
    volumes:
      - .data/mysqldb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tor
      - MYSQL_USER=toruser
      - MYSQL_PASSWORD=torpass
      - MYSQL_ROOT_PASSWORD=rootpass
    command:
      - --max_allowed_packet=256M
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --net_read_timeout=30
      - --net_write_timeout=60
      - --connect_timeout=10
      - --max_connections=1000
      - --skip-name-resolve
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: "darkweb-search-engine-db"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "toruser",
          "-ptorpass",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  #  web-general:
  #    build: ./web-general  # Path to the Dockerfile for web-general
  #    restart: always
  #    ports:
  #      - "0.0.0.0:7000:5000"
  #    volumes:
  #      - ./etc:/opt/torscraper/etc:ro
  #      - ./scripts:/opt/torscraper/scripts:ro
  #      - ./lib:/opt/torscraper/lib:ro
  #      - ./web-general:/opt/torscraper/web
  #    depends_on:
  #      - db
  #      - elasticsearch1
  #      - elasticsearch2
  #    container_name: "darkweb-search-engine-web-general"
  #    logging:
  #      driver: json-file
  #      options:
  #        max-size: 2000k
  #        max-file: '10'

  #  db:
  #    build: db
  #    ports:
  #      - "0.0.0.0:3307:3306"
  #    volumes:
  #      - .data/mysqldb:/var/lib/mysql
  #    container_name: "darkweb-search-engine-db"
  #    logging:
  #      driver: json-file
  #      options:
  #        max-size: 2000k
  #        max-file: '10'

  #   crawler:
  #     build: .
  #     restart: always
  # #    deploy:
  # #      resources:
  # #        limits:
  # #          cpus: '6'
  # #          memory: 14G
  # #        reservations:
  # #          cpus: '0.6'
  # #          memory: 4G
  #     ports:
  #       - "3128"
  #     depends_on:
  #       - db
  #       - elasticsearch
  #     container_name: "darkweb-search-engine-crawler"

  tor-privoxy0:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy0"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy1:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy1"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy2:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy2"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy3:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy3"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy4:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy4"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy5:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy5"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy6:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy6"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy7:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy7"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy8:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy8"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"
  tor-privoxy9:
    restart: always
    build: tor-privoxy-scraper
    container_name: "darkweb-search-engine-tor-privoxy9"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"

  tor-privoxy-web:
    restart: always
    build: onion_proxy
    ports:
      # - "9050:9050" # Tor proxy
      - "3100:8100" # Privoxy
    container_name: "darkweb-search-engine-tor-privoxy-web"
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: "10"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
